# Ubuntu 14.04 (but also works on other releases)
dist: trusty

# Use the container-based infrastructure
sudo: false
addons:
  apt:
    packages:
    # General build process
    - make
    # For light system
    - libmono-system-core4.0-cil
    - libmono-system-drawing4.0-cil
    # For Impulse audio library
    - libpulse-dev
    - libfftw3-dev

language: csharp
solution: Actinic.sln

script:
  - make all
