# Ubuntu 14.04 (but also works on other releases)
dist: trusty

# Use the container-based infrastructure
sudo: false
addons:
  apt:
    packages:
    # General build process
    - make
    # For light system
    - libmono-system-core4.0-cil
    - libmono-system-drawing4.0-cil
    # For Impulse audio library
    - libpulse-dev
    - libfftw3-dev

language: csharp
solution: Actinic.sln

# Prepare the test framework, too
install:
  - nuget restore Actinic.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

# Run build, then tests
script:
  - make all
  - make tests
